### ISSUE TITLE
Doesn't work well with themes

### ISSUE THREAD

**Issue by maciek-1234** [12944qwerty/profile-stats#1]
As the background and font colors are hard coded, the stats stand out a lot when using a theme.

This is how it looks for me ([theme](https://github.com/orblazer/discord-nordic)):
![image](https://user-images.githubusercontent.com/74118490/162792317-ec91c7b4-783d-45af-8ca2-29cde4c7129b.png)

**Comment by 12944qwerty** [comment]
Should be fixed now thanks to #3
